# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: 2022 Kent Gibson <warthog618@gmail.com>
# SPDX-FileCopyrightText: 2024 Bartosz Golaszewski <bartosz.golaszewski@linaro.org>

# This file is part of libgpiod.
#
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path("../bindings/python").resolve()))

project = "libgpiod"
copyright = "2017-2024, Bartosz Golaszewski"
author = "Bartosz Golaszewski"

# Extract the full version from configure.ac (including -devel, -rc and other
# tags).
with open("../configure.ac", "r") as fd:
    version = ""
    extra = ""
    for line in fd.readlines():
        match = re.search(r"AC_INIT\(\[libgpiod\], \[(.*?)\]\)", line)
        if match:
            version = match.group(1)
            continue

        match = re.search(r"AC_SUBST\(EXTRA_VERSION, \[(.*?)\]\)", line)
        if match:
            extra = match.group(1)

        release = f"{version}{extra}"

subprocess.run(["doxygen", "Doxyfile"])

cwd = os.getcwd()
os.chdir("..")
subprocess.run(["autoreconf", "-ifv"], check=True)
subprocess.run(
    [
        "./configure",
        "--enable-tools",
        "--enable-bindings-glib",
        "--enable-introspection",
        "--enable-tools",
    ],
    check=True,
)
subprocess.run(["make", "-j"], check=True)
os.chdir(cwd)


def make_glib_docs(app):
    # For some reason on RTD we're in the docs/ directory while during a local
    # build, we're still in the top source directory.
    prefix = "../" if os.getenv("READTHEDOCS") == "True" else ""

    subprocess.run(
        [
            "gi-docgen",
            "generate",
            "--config",
            f"{prefix}bindings/glib/gi-docgen.toml",
            f"{prefix}bindings/glib/Gpiodglib-1.0.gir",
            "--output-dir",
            f"{app.outdir}",
        ],
        check=True,
    )


def make_gpio_tools_docs(app):
    prefix = "../" if os.getenv("READTHEDOCS") == "True" else ""

    os.makedirs(f"{app.outdir}/gpio-tools", exist_ok=True)

    for tool in [
        "gpiodetect",
        "gpioinfo",
        "gpioget",
        "gpioset",
        "gpiomon",
        "gpionotify",
    ]:
        with open(f"{app.outdir}/gpio-tools/{tool}.html", "w") as fd:
            subprocess.run(
                ["man2html", f"{prefix}man/{tool}.man"], stdout=fd, check=True
            )


late_docs_funcs = [make_glib_docs, make_gpio_tools_docs]


def setup(app):
    app.connect("builder-inited", make_docs_late)


# We need to know where to put docs generated by means other than sphinx but
# app.outdir is only set once the builder is initialized. Let's delay running
# some tools until we're notified.
def make_docs_late(app):
    for func in late_docs_funcs:
        func(app)


master_doc = "index"
source_suffix = ".rst"

extensions = ["breathe", "sphinx.ext.autodoc"]

breathe_projects = {"libgpiod": "./doxygen-output/xml"}
breathe_default_project = "libgpiod"

autodoc_mock_imports = ["gpiod._ext"]

# Use the RTD theme if available
sphinx_rtd_theme = None
try:
    import sphinx_rtd_theme

    extensions.append("sphinx_rtd_theme")
except ImportError:
    pass

html_theme = "sphinx_rtd_theme" if sphinx_rtd_theme else "default"
