# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: 2024 Vincent Fazio <vfazio@gmail.com>

class Chip:
    def __init__(self) -> None: ...
    def set_label(self, label: str) -> None: ...
    def set_num_lines(self, num_lines: int) -> None: ...
    def set_line_name(self, offset: int, name: str) -> None: ...
    def set_hog(self, offset: int, name: str, direction: int) -> None: ...
    def enable(self) -> None: ...
    def get_value(set, offset: int) -> int: ...
    def set_pull(set, offset: int, pull: int) -> None: ...
    @property
    def dev_path(self) -> str: ...
    @property
    def name(self) -> str: ...

PULL_DOWN: int
PULL_UP: int
VALUE_INACTIVE: int
VALUE_ACTIVE: int
DIRECTION_INPUT: int
DIRECTION_OUTPUT_HIGH: int
DIRECTION_OUTPUT_LOW: int
